name: 'Source Branch Enforcer'
on:
  pull_request:
    branches:
      - main

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify dev is the source
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: Merges to 'main' are only allowed from the 'dev' branch."
          exit 1